# Generated by Django 4.0.5 on 2022-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_profile_surname_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buldingNumber',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='houseNumber',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
