# Generated by Django 4.0.5 on 2022-06-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_profile_buldingnumber_profile_housenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='buldingNumber',
            new_name='buildingNumber',
        ),
    ]
