# Generated by Django 4.0.5 on 2022-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/products/default.jpg', height_field=800, upload_to='static/images/products', width_field=1200),
        ),
    ]
