# Generated by Django 4.0.5 on 2022-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/products/default.jpg', upload_to='static/images/products'),
        ),
    ]
