# Generated by Django 4.0.5 on 2022-07-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_full_price_order_payment_method_deliveryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
